### ISSUE TITLE
Support LADP and Linux authentication when region is Edge.

### ISSUE THREAD

**Issue by macrovve** [grafana/iot-sitewise-datasource#100]
SiteWise Edge now support LDAP and Linux authentication, SiteWise plugin should be able to support this as well. 

When customer want to access data in the edge, they need to call `/authenticate` API first to get temporary AWS credentials which will expire after 4h. And they will use OpsHub to download their certificate. With AWS credentials and certificate, they could call SiteWise data plane API to fetch data. 

There two changes need to be made on the plugin:
* Provide a way to allow customer to enter their LDAP/Linux credential
* Implement a mechanism to refresh credential every 4h
* Support AWS session token, It only supports AWS access key and secret key now.

**Comment by atifali** [comment]
feature merged - closing this.
