### ISSUE TITLE
Add Variable Query editor

### ISSUE THREAD

**Issue by tracfren** [grafana/iot-sitewise-datasource#113]
There are no query types available for IoT SiteWise when defining a variable based on a query. Can we support querying by asset using the ListAssets API?

**Comment by tracfren** [comment]
Desired UX: We want users to be able to pick an active asset (based on a query) or select from a list of currently running processes.

Preferred Solution: Define a variable in Grafana using a sitewise query. The result needs to be comma-separated name:value pairs with the name being the asset name and the value the asset ID.

**Comment by taleena** [comment]
**Existing workaround:**
Query the data (batches, assets) from a different data source (e.g. Athena)  while populating a dashboard variable. Alternatively, hard code the asset IDs. This makes the deployment process more complex.

Of the recently reported issues, this is the 1st priority.

**Comment by taleena** [comment]
Customer does not consider the workarounds as feasible, so we need to provide an estimated timeline.

**Comment by lean257** [comment]
Hi @tracfren @taleena I just merged a change to this issue, would you be able to check and verify to close the issue? Thanks!

**Comment by taleena** [comment]
I've sent a heads up to the requestor, haven't heard anything back yet but please feel free to proceed!

**Comment by toddtreece** [comment]
this has been released in v1.3.0:
https://github.com/grafana/iot-sitewise-datasource/releases/tag/v1.3.0
https://grafana.com/grafana/plugins/grafana-iot-sitewise-datasource/
