### ISSUE TITLE
Show variable name in panel edit mode when Asset is referencing a variable

### ISSUE THREAD

**Issue by tracy-french** [grafana/iot-sitewise-datasource#114]
We can reference an asset ID in a variable just fine, but it is not showing up as a variable in the UI, making it confusing to know which are and which are not variables.

![Screen Shot 2022-03-01 at 8 28 01 AM](https://user-images.githubusercontent.com/67283114/156197879-4bf0b0c5-56e2-4307-bc68-e68e2bd83ca9.png)

**Comment by taleena** [comment]
**Desired functionality:**
Show the variable name in panel edit mode when an Asset is referencing a variable. We want the panel to reflect the fact that the asset field is referencing a variable. This works well for the property field but not for asset-id

**Suggested solution:**
Have the asset field work like the property field does

**Existing workaround:**
Open the JSON file to see what the actual value is

**Comment by katebrenner** [comment]
closing as fixed
