### ISSUE TITLE
Variable in alias field

### ISSUE THREAD

**Issue by tracfren** [grafana/iot-sitewise-datasource#116]
Is it not possible to use a variable in an alias field (i.e., failed to fetch query data: ResourceNotFoundException: Property not found (Property Alias = /Units/${machine}/Sensors/Temperature/Value))?

**Comment by taleena** [comment]
Hi @tracfren - this is another that would benefit from some more context or additional information, or even better some repro step so we can see that error ourselves and better understand what you are attempting.

**Comment by taleena** [comment]
Closing as there has been no response and we are unable to proceed with the given information. Please reopen if needed!
