### ISSUE TITLE
Filter query results

### ISSUE THREAD

**Issue by tracfren** [grafana/iot-sitewise-datasource#117]
Is it possible to filter the results of a query?

**Comment by taleena** [comment]
Hi @tracfren - This is a very generic question, perhaps you can provide some more context or specific example of what you are trying to accomplish?

**Comment by ryantxu** [comment]
Likely https://grafana.com/docs/grafana/latest/panels/transform-data/ is the best path -- this lets you use results then change their shape before passing it to a visualization.
