### ISSUE TITLE
Create dynamic data links with variables as parameters

### ISSUE THREAD

**Issue by tracfren** [grafana/iot-sitewise-datasource#118]
Desired UX: Create dynamic links from one dashboard to another without having to hardcode parameters for every bioreactor.

Preferred solution: Want to be able to use something like ${__data.fields.<any field>} to access the asset-id & timestamp and pass it as a parameter in a link.

**Comment by taleena** [comment]
Of the recently reported requests, this is 3rd in priority.

**Desired functionality:**
Create dynamic links from one dashboard to another without having to hardcode parameters for every bioreactor.

**Suggested Solution:**
Want to be able to use something like ${__data.fields.<any field>} to access the asset-id & timestamp and pass it as a parameter in a link.

**Existing workaround:**
Create separate panels one for each asset and hard code the asset IDs in the data links. It is a maintenance burden and needs to be updated for each environment.

**Comment by ryantxu** [comment]
What is source query and result?  Is there a reason we can not use `${__data.fields.}`?    Is the problem that you want the query value as part of the link?

**Comment by taleena** [comment]
@tracfren Are you able to provide the answer to the above?

**Comment by roygv** [comment]
I want to be able to pass the asset name from the original Sitewise query as a parameter to another dashboard to implement a drill-down

**Comment by toddtreece** [comment]
@roygv if i am understanding correctly, it seems like you could use dashboard variables for this workflow. 

1. define a variable for the assets:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/360020/183565584-1879d4b9-0e79-4898-ac36-166b869fe304.png">

2. add the variable to your panel query:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/360020/183565689-5a7d3046-a620-4a24-b6db-d3665bc96a35.png">

3. add the variable to a panel data link:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/360020/183565762-3275d7dd-e416-49b1-ac62-cbf2c449a4c0.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/360020/183565823-862569fa-3205-4e49-9533-2ba3e42c4753.png">

4. repeat steps 1 & 2 for the target dashboard using the same variable name (in this example `query0`)

5. click on a data link in the source dashboard, and it should set the variable in the target dashboard. in my example, the link URL ends up looking like this when it's rendered

```
http://localhost:3000/d/4AtLr7kVz/1-state-timeline?var-query0=e64c9075-9d89-47cb-8ee5-d3251bd253f4&orgId=1
```

**Comment by taleena** [comment]
@roygv Did this work for you? We're closing for not, but please reopen if it is not resolved for you.
