### ISSUE TITLE
Panel does not show the list of asset models when an asset model has no description

### ISSUE THREAD

**Issue by lejeuneretif** [grafana/iot-sitewise-datasource#122]
When an asset model in IoT SiteWise does not have any description, the panel with a **Query Type** on **List asset models** shows **No data in response**. When exploring this panel, the **Query error Metric request error** shows up.

These errors do not show when all the asset models have a description.

Minimal Reproducible Example:
- in the Console of IoT SiteWise, create the demo if there is no asset models, and a dummy model with an empty description,
- in a Grafana instance:
  - create the IoT SiteWise Data Source,
  - create a dashboard with a panel with **Query Type** as **List asset models** -> the panel says **No data in response**,
  - explore the panel -> the error **Query error Metric request error** shows.
- back in the Console of IoT SiteWise, add a description to the dummy asset model,
- refresh the page of the exploration of the panel -> the list of asset models shows, and the panel itself does not say **No data in response** anymore.

The description if an optional field of the asset models, the plugin should not show any error when this optional field is missing.

The Grafana logs contain these errors around the time when this issue occurs:
```
failed to query data: Failed to query data: rpc error: code = Canceled desc = context canceled

failed to query data: Failed to query data: rpc error: code = Unavailable desc = error reading from server: EOF
```

We think the plugin crashes on empty description.

**Comment by atifali** [comment]
fixed in the release v1.2.6: https://github.com/grafana/iot-sitewise-datasource/releases/tag/v1.2.6
