### ISSUE TITLE
[Request]: Amazon Managed Grafana - Support for filters based on Sitewise tags

### ISSUE THREAD

**Issue by jaiakhil** [grafana/iot-sitewise-datasource#149]
Customers want the dashboards to be filtered based on one or the other property from sitewise. For e.g., viewing the data for a particular shift or a  particular batch. They cannot do it today.

**Comment by taleena** [comment]
Hello @jaiakhil we will need some more information to better address your request, would you mind providing some additional context?

**What are you really trying to do?**
_Brief description of what you are trying to accomplish and why._

**Context and constraints**
_Details to help us better understand the problem. For example, is this something that already works in [AWS's console](https://console.aws.amazon.com/iotsitewise/)?_

**Describe what you've already tried and where it falls short**
_Our first response could be asking you to try something you’ve already done, so instead, let us know why the current solution is insufficient. Maybe we’ll be able to point out something that will work as an interim solution. Screenshots or recordings can be helpful here._

**Additional context**
_Any other context or screenshots about the feature request you think would help us out._

**Environment**
- Grafana version:
- Data source version:
- OS Grafana is installed on:
- User OS & Browser:
