### ISSUE TITLE
failed to fetch query data: : Unknown Operation status code: 404, request id:

### ISSUE THREAD

**Issue by misiek303** [grafana/iot-sitewise-datasource#161]
I am unable to query data anymore.  I get the below error:

```
failed to fetch query data: : Unknown Operation status code: 404, request id:
```
Grafana Logs:

```
logger=context userId=1 orgId=1 uname=admin t=2023-02-06T10:38:36.314059731-06:00 level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=192.168.50.132 time_ms=18 duration=18.094402ms size=137 referer="http://192.168.50.248:3000/d/YUUwUxA4k/txrx-simulator?orgId=1&refresh=5s" handler=/api/ds/query
```

**Environment**:
- Grafana version: 9.3.6
- Plugin version: 1.6.1
- OS Grafana is installed on: Ubuntu Server 20.10 LTE
- Data Processing Pack: 2.1.29

![Screenshot 2023-02-06 at 10 37 33 AM](https://user-images.githubusercontent.com/371344/217030313-662e70ec-8ee2-4ae1-b91b-5481bc11684c.png)

Connection to the Datasource works just fine

![Screenshot 2023-02-06 at 10 38 48 AM](https://user-images.githubusercontent.com/371344/217030615-ce1a059c-0dbc-41bc-becc-c98f0407126d.png)

I am also able to use AWS OpsHub and see all models, assets, and the latest data

<img width="1413" alt="Screenshot 2023-02-06 at 10 40 06 AM" src="https://user-images.githubusercontent.com/371344/217031355-8e508433-f17a-4d1f-8aea-805a83433ec1.png">

<img width="1429" alt="Screenshot 2023-02-06 at 10 40 22 AM" src="https://user-images.githubusercontent.com/371344/217031320-4f5373e3-d482-4b49-b59d-e19905f06d46.png">

Can you help ?

**Comment by Vijay-Karthick** [comment]
I can confirm the same. With latest version, 'Get property value history' or any similar APIs were not displaying asset selection. In fact, the drop-down menu for asset selection and property selection were missing. I had to downgrade to 1.5.1 and everything started working as expected.

However, in latest version, list assets and list asset models were working fine.

**Comment by katebrenner** [comment]
close as completed in https://github.com/grafana/iot-sitewise-datasource/pull/281
