### ISSUE TITLE
How do I use Boolean type in alert rules

### ISSUE THREAD

**Issue by misiek303** [grafana/iot-sitewise-datasource#162]
There is no way to set a condition that is in boolean format. Below is my use case

A: query:
 - outputs if the machine is running or not. The output is the INTEGER type as the status machine code
 - condition is using range option: VALUE > INTEGER < VALUE

B: query:
- outputs if the machine is scheduled or not. The output is the. BOOLEAN
- missing condition: VALUE = True

A simple transformation would work as well, but I can't find a way even using expressions.

Any ideas?

**Comment by idastambuk** [comment]
Hi @misiek303,

Grafana alerting doesn't support booleans as alert values or transforming a boolean value to get an alert rule in Grafana. 
However, there should be a way to transform boolean values on AWS SiteWise side to 1 and 0 and then make a math alert rule out of that. Can you try following the steps below and see if that does what you need it to? 

1. Click the Edit in the Asset Model configuration for your asset and scroll down to the Transform tab. This is what that looks like in the console: 
<img width="550" alt="Screen Shot 2023-02-21 at 3 19 46 PM" src="https://user-images.githubusercontent.com/16140639/220370534-f325d555-7419-42d2-9589-25856cac43a8.png">

2. Add a transform rule for one of your measurements. "if" and "eq" for strings should give you what you need, maybe another one from [here](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/transforms.html) too, but this is what worked for me
<img width="550" alt="Screen Shot 2023-02-21 at 3 23 10 PM" src="https://user-images.githubusercontent.com/16140639/220371162-b7567fea-4ce6-49f0-a7fa-6668a74d60bd.png">

3. Once you Save and re-query the asset in Grafana panel, you should have the new field (isSW, for example) in the asset property list. It will return an array of 0s or 1s for for the time series. If you use this query as the input for your Threshold rule (or use a [Math expression](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/#math)), you should be able to create an alert that fires when >0, or the machine is scheduled. 

<img width="479" alt="Screen Shot 2023-02-21 at 3 25 15 PM" src="https://user-images.githubusercontent.com/16140639/220371838-7498f3f8-6720-4ca6-8641-ad730430caf0.png">


Hope this helps!

**Comment by fridgepoet** [comment]
Closing as this is stale
