### ISSUE TITLE
Property aggregate query causes panic if the call to BatchGetAssetPropertyAggregatesPagesWithContext needs to be paged

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/iot-sitewise-datasource#182]
**What happened**:

Run a property aggregate query with resolution set to auto and increase the time range until it causes the call to [BatchGetAssetPropertyAggregatesPageAggregation](https://github.com/grafana/iot-sitewise-datasource/blob/9ea952893e9da5f8f719ecc1dd462311d34ea3ac/pkg/sitewise/client/client.go#L44) needs to be paged.

This causes a panic because there is a mismatch of expectations when building the frames because we assume the success entries is flat with each item representing a single asset https://github.com/grafana/iot-sitewise-datasource/blob/9ea952893e9da5f8f719ecc1dd462311d34ea3ac/pkg/framer/property_aggregate.go#L109-L110

See original comment on this issue here https://github.com/grafana/iot-sitewise-datasource/pull/179#issuecomment-1535064145

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by sarahzinger** [comment]
Moving this to Next since I see a [user](https://github.com/grafana/iot-sitewise-datasource/issues/195) is running into this issue

**Comment by kevinwcyu** [comment]
this should be fixed by #194 as well
