### ISSUE TITLE
Regression in query by propertyAlias for unmodeled data

### ISSUE THREAD

**Issue by diehbria** [grafana/iot-sitewise-datasource#185]
**What happened**:

Query by propertyAlias fails in grafana9 (but works in grafana8) for data that is unassociated to any SiteWise models.

Getting return error: 

> failed to fetch query data: InvalidRequestException: Entries size failed to satisfy constraint: Must be at least 1 entry per request.

**What you expected to happen**:

Query by propertyAlias to return succesfully 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I'm speculating that this regression is related to the introduction of the batch API

**Comment by sparkgene** [comment]
I met the same problem too. Same settings worked with Managed Grafana v8.4 + Sitewise Plugin v1.5.1.

**Comment by kevinwcyu** [comment]
Hi, can you try v1.9.0 of the SiteWise Plugin to see if the property alias query works?

**Comment by jhoulihan** [comment]
Hi kevinwcyu, is there a way to use the new plugin, in AWS managed grafana for me to test functionality?  
If it helps, using an unmodelled data stream and querying for interpolated data produces a time series, but not the other query types currently, using AMG grafana v9. As above comment by sparkgene, using unmodelled...or (using AWS sitewise terms) disassociated data streams , all queries work in AMG grafana v8

**Comment by sparkgene** [comment]
I'm using AMG v9.4. And the installed SiteWise plugin is 1.7.0. Can we update the plugin to the latest version?

**Comment by sarahzinger** [comment]
@jhoulihan @sparkgene are you all able to upgrade the sitewise plugin by following these steps: https://grafana.com/docs/grafana/latest/administration/plugin-management/#update-a-plugin

**Comment by jhoulihan** [comment]
@sarahzinger thank you for reverting! I don't appear to be able to with Amazon Managed Grafana. I can see the updated plugin listed, evidencing the hard work the developers put in (Thank you all!)  I'll follow up with my supportive local associate.

**Comment by sarahzinger** [comment]
Great, I'll close this issue for now then but feel free to open a new one if after upgrading the bug does not go away. Thanks again for reporting!
