### ISSUE TITLE
Link for feature 

### ISSUE THREAD

**Issue by jhoulihan** [grafana/iot-sitewise-datasource#191]
Hi all, at this risk of crossposting  and perhaps causing offence (and not being my intent), I posted this feature request via discussion for comment please, https://github.com/grafana/iot-sitewise-datasource/discussions/186 . I understand everybody is busy 🙌

**Comment by sarahzinger** [comment]
Hi @jhoulihan thanks for submitting this feature request! Unfortunately we don't have a timeline yet on getting to this feature request but next time we're revisiting overall enhancements to this datasource we'll be sure to revisit this idea!

**Comment by katebrenner** [comment]
closing as stale
