### ISSUE TITLE
Get property value aggregates: display name changes with resolution

### ISSUE THREAD

**Issue by egheie** [grafana/iot-sitewise-datasource#198]
**What happened**: 
Field name of a property changes when resolution changes from >= MINUTE to RAW.  Happens for a single query as well as multiple queries in the same panel. 

**What you expected to happen**: 
Expect the field name to remain the same and include the property name to make it easy to identify. Can be worked around for standard panels with Field Override --> Fields returned by query. 

Becomes an issue for custom built panels which require a way to identify queries based on names, and all names are "raw" without the name of the property.

**How to reproduce it (as minimally and precisely as possible)**: 
1 . Query type `Get property value aggregates` with Aggregate `Average` resolution `Auto`.
2. Set time frame to be greater than 20 min (should be *average* values)
3. See DataFrame JSON and value of the key "name" under "schema". This includes the property name. 
4. Change time frame to < 15 min (should be *raw* values)
5. See DataFrame JSON and value of the key "name" under "schema". This does not include the property name. 

**Screenshots**
![image](https://github.com/grafana/iot-sitewise-datasource/assets/114905807/fd959fdf-666f-4510-9675-b0ff9d2facb3)
Screenshot of step 3
![image](https://github.com/grafana/iot-sitewise-datasource/assets/114905807/ba729022-5873-4b85-a898-393dbbd8e4fa)
Screenshot of step 5

**Environment**:
- Grafana version: 10.0.0
- Plugin version: 1.9.2
- OS Grafana is installed on: Docker Ubuntu base image
- User OS & Browser: Windows & Chrome
- Others:

**Comment by idastambuk** [comment]
Hi @egheie, thanks for submitting this!

I notice that in your description you mention 
> and all names are "raw" without the name of the property.

But in the Steps to reproduce and screenshots you refer to the frame name (which doesn't include "raw" anywhere). Can you clarify which field is the one that's causing the problem?
1. The frame name not being "AssetName PropertyName" or
2. The field name being "raw" and not "avg" when the auto resolution is changed?

Thanks!

**Comment by egheie** [comment]
Hi @idastambuk, thank you for the response. 

Sorry, that might not have been clear enough. 

The screenshots above show how the frame name changes when the timeframe changes, or when the API call changes from _GetAssetPropertyAggregate_ to _GetAssetPropertyValueHistory_. If including a legend to a time series panel for the _Steps to reproduce_, with 1 or more queries, the legend says (see screenshots below):
-  "raw" when resolution is "raw"
- "AssetName PropertName avg" (for multiple queries) when resolution is minute, hour or day
- "avg" for a single query when resolution is minute, hour or day.


![image](https://github.com/grafana/iot-sitewise-datasource/assets/114905807/b2c01fed-9af2-410f-ae28-1c5944672fc2)

![image](https://github.com/grafana/iot-sitewise-datasource/assets/114905807/99ad6d14-e490-48ff-9664-f5421fd7c8b7)

The problem is when two different properties from the same asset ending up having same name when resolution is switched to 'raw'. I expect them to different since it is different properties, so if that is what you mean by:

> 1. The frame name not being "AssetName PropertyName" 

Then yes, this is what is causing the problem. 

Sorry for the lengthy response, hope it explained the problem in a clearer way so have the same understanding of the issue. 

Thanks for the support!

**Comment by idastambuk** [comment]
Hi @egheie I think I understand what you mean now. Just to confirm, this legend: 

![246409151-b2c01fed-9af2-410f-ae28-1c5944672fc2](https://github.com/grafana/iot-sitewise-datasource/assets/16140639/05b71b1e-15ea-4805-9f9f-64d9f03ab8fa)

  should say: `AssetName PropertyName1 raw; AssetName PropertyName2 raw`,
  to follow the same naming convention as `avg` when two properties are present?

**Comment by egheie** [comment]
Hi @idastambuk, 

Yes, that would be a way of solving it. The main thing is to have a field (e.g. in line 17 in the first screenshot) that does not change when the resolution changes (this is happening currently), if that is possible? 

That would make this issue go away for us, so we are able to reference it in custom panel plugins.

**Comment by idastambuk** [comment]
Hi again @egheie I think it would help to know which field/name you're trying to capture with your custom plugin: 

 Line 17 you refer to in the Data Frame JSON is the **frame name**. Currently it's just the AssetName ('test') for "raw" queries. It does make sense to me to change it to AssetName PropertyName ('test testName'). If we do this, this won't change when switching from 'avg' to 'raw'. 

When it comes to **field name** (currently "raw", type number in the 2nd screenshot), since the auto resolution changes to "raw", I don't think it would make sense to have it remain 'avg'. The only thing that we can do is add the asset and property names like: `AssetName PropertyName1 raw`. Just the final word will change when switching from 'avg' to 'raw'.

Thanks for helping me clarify this!

**Comment by egheie** [comment]
Hi @idastambuk, thank for for the response, appreciate the support you and the team provides. 

> Line 17 you refer to in the Data Frame JSON is the frame name. Currently it's just the AssetName ('test') for "raw" queries. It does make sense to me to change it to AssetName PropertyName ('test testName'). If we do this, this won't change when switching from 'avg' to 'raw'.

I agree with this, and that would solve it for us. 

> When it comes to field name (currently "raw", type number in the 2nd screenshot), since the auto resolution changes to "raw", I don't think it would make sense to have it remain 'avg'. The only thing that we can do is add the asset and property names like: AssetName PropertyName1 raw. Just the final word will change when switching from 'avg' to 'raw'.

Also agree with this. The field name should reflect the actual resolution ("raw" if it **raw**, and "avg" if it is **average**.) Not important for our case if the final word is there or not, it is the point above which is causing the issue.

**Comment by idastambuk** [comment]
Hi @egheie, we just released the new version of the plugin (1.10.0) with the fix :)

**Comment by egheie** [comment]
Hi @idastambuk, thank you for your quick fix.
