### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/iot-sitewise-datasource#212]
[E2E testing docs](https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/introduction)

Add tests for
- [x] Config Editor: https://github.com/grafana/iot-sitewise-datasource/issues/212
- [x] Query Editor

Tasks
- [x] Remove things referencing cypress, @grafana/e2e, @grafana/e2e-selectors (if they still exist) in package.json, config files, etc.
- [x] Add scripts for `playwright:test` to run the tests, `playwright:report` to show the report. Update the github workflow to use `playwright:test` instead of `yarn playwright test` and update documentation.
- [ ] #311

**Comment by sarahzinger** [comment]
A lot of this was already done by others, but I'll just verify that there's nothing else  that needs to be done and close this out.

**Comment by sarahzinger** [comment]
I'm going to close this ticket for now, since we do have e2e tests for both the query editor and config editor, but there is still one lingering issue that we deprioritized which I've added to the backlog: https://github.com/grafana/iot-sitewise-datasource/issues/311
