### ISSUE TITLE
Feature: support for Lookout for Equipment (L4E) complex data types

### ISSUE THREAD

**Issue by taleena** [grafana/iot-sitewise-datasource#219]
### Discussed in https://github.com/grafana/iot-sitewise-datasource/discussions/217

<div type='discussions-op-text'>

<sup>Originally posted by **diehbria** September 13, 2023</sup>
This is a request to introduce support for [L4E](https://docs.aws.amazon.com/lookout-for-equipment/latest/ug/what-is.html) support into the Grafana SIteWise plugin. A high level explanation of L4E (lookout for equipment) can be found in this [amazon blog post](https://docs.aws.amazon.com/lookout-for-equipment/latest/ug/what-is.html).

Users of SiteWise that also utilize L4E would like to be able to view and understand the anomolies detected by L4E within their grafana dashboards with the SiteWise Plugin.

L4E information in SiteWise is stored as a structured string, which is refered to as a "complex data type". Below is the expected structure for the L4E complex data type:

```
        value: {
          stringValue: `{"anomalyScore": ${anomalyScore} }`,
        },
```

an asset property which represents the L4E anomoly score may be identified through the `dataSpecType` as follows:

```
assetProperty.dataTypeSpec === 'AWS/ANOMALY_LOOKOUT_METRICS_RESULT' // if this is true, the asset property represents L4E anomaly data
```

---

High level use cases:

- users should be able to easily identify which of their asset properties represent anomaly scores
- users should be able to visualize the anomoly scores on their dashboard

Below is an example of how a user may want to be able to explore their anomoly scores:
<img width="712" alt="Screenshot 2023-09-13 at 8 46 49 PM" src="https://github.com/grafana/iot-sitewise-datasource/assets/77755322/5ff4a640-7eca-432c-86a5-068b3adcb0c2">

In this example, the chart visualizes the periods in time with anomalies. An anomaly score of 1 is interpreted as an anomoly has occured at the given point in time. An anomoly score of 0 is interpreted as no anomaly is associated with the given point in time.
</div>

**Comment by iwysiu** [comment]
finished in linked pr
