### ISSUE TITLE
One dashboard with different time periods

### ISSUE THREAD

**Issue by fridgepoet** [grafana/iot-sitewise-datasource#223]
### Discussed in https://github.com/grafana/iot-sitewise-datasource/discussions/220

<div type='discussions-op-text'>

<sup>Originally posted by **misiek303** September 20, 2023</sup>
Hi

We have a request to build a dashboard for graphs that load data from different time periods. For instance: One graph displays statistics by month, the other graph loads data for the last 7 days and the other some real-time information.

Is there any workaround I can achieve it or is there a feature like this on the roadmap?
Thanks
</div>

**Comment by jhoulihan** [comment]
The following post is helpful to use the panel Query Options "Relative time eg: 1w/w" https://community.grafana.com/t/how-to-shift-date-of-data-and-how-to-set-per-graph-time-range/48610/4

**Comment by idastambuk** [comment]
Thanks @jhoulihan for providing the info! I agree that Relative time in Query options dropdown can be used to override the dashboard time picker. 

![Image](https://github.com/grafana/iot-sitewise-datasource/assets/16140639/1c842fcd-99ed-47c1-b50d-4efb1476555d)

More info can be found in the docs here: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/#query-options

**Comment by misiek303** [comment]
That's great. But I can't choose a specific time from, for example from 1 day of the month until now, can I ?

**Comment by idastambuk** [comment]
Indeed not, these just for relative times for now and just with the options described in the docs table. 
For now we don't plan on having a specific Sitewise time picker, so I'll close this issue, but there is a feature request in main Grafana repo to change this ([here](https://github.com/grafana/grafana/issues/6558)) so I suggest upvoting it as a first step. 
Furthermore, the Scenes project is planned to introduce panel-based time pickers, the epic of which is [here](https://github.com/grafana/grafana/issues/73874), so you can follow the progress of that one too.
