### ISSUE TITLE
Issue with query variables causing InvalidParameter failures 

### ISSUE THREAD

**Issue by zspeaks** [grafana/iot-sitewise-datasource#227]
**What happened**:
When attempting to use query variables in a get property value query, I receive the following error:
`failed to fetch query data: InvalidParameter: 1 validation error(s) found. - minimum field size of 36, BatchGetAssetPropertyValueInput.Entries[0].AssetId.`

If I instead manually select the asset, the otherwise exact same configuration works correctly. 

**What you expected to happen**:
Should be able to use query variables in panels. 
Alternatively, if this was an intended breaking change, let me know. 

Additionally, if a known workaround exists, please let me know. 

**How to reproduce it (as minimally and precisely as possible)**:
Create dashboard query variable, using either a list assets or list associated assets query
Attempt to use this query variable in a get asset data query, in a dashboard panel

**Screenshots**
<img width="1578" alt="Screenshot 2023-10-09 at 12 04 38 PM" src="https://github.com/grafana/iot-sitewise-datasource/assets/68298466/1f52ee80-e609-41ba-9404-bba83ee531ca">

<img width="1572" alt="Screenshot 2023-10-09 at 12 04 55 PM" src="https://github.com/grafana/iot-sitewise-datasource/assets/68298466/20487e6d-de63-4f5e-8e0b-38e3b25a774e">

<img width="1575" alt="Screenshot 2023-10-09 at 12 05 01 PM" src="https://github.com/grafana/iot-sitewise-datasource/assets/68298466/8246e2c8-e062-4614-b62c-ef036f663a8e">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Plugin version: 1.10.1
- OS Grafana is installed on: 
- User OS & Browser: MacOS, Firefox
- Others:

**Comment by zspeaks** [comment]
Query Inspector when trying to use the variable:
{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 \{\
  "request": \{\
    "url": "api/ds/query",\
    "method": "POST",\
    "data": \{\
      "queries": [\
        \{\
          "datasource": \{\
            "type": "grafana-iot-sitewise-datasource",\
            "uid": "URhhbtMSk"\
          \},\
          "refId": "A",\
          "maxPageAggregations": 1,\
          "queryType": "PropertyValue",\
          "assetIds": [\
            "Demo Wind Farm Asset"\
          ],\
          "propertyId": "53df0857-d5a3-44f4-a946-bcbf0461a8a6",\
          "propertyAlias": "",\
          "region": "",\
          "datasourceId": 7,\
          "intervalMs": 500,\
          "maxDataPoints": 768\
        \}\
      ],\
      "range": \{\
        "from": "2023-10-09T19:05:44.796Z",\
        "to": "2023-10-09T19:10:44.797Z",\
        "raw": \{\
          "from": "now-5m",\
          "to": "now"\
        \}\
      \},\
      "from": "1696878344796",\
      "to": "1696878644797"\
    \},\
    "hideFromInspector": false\
  \},\
  "response": \{\
    "results": \{\
      "A": \{\
        "error": "failed to fetch query data: InvalidParameter: 1 validation error(s) found.\\n- minimum field size of 36, BatchGetAssetPropertyValueInput.Entries[0].AssetId.\\n",\
        "status": 500,\
        "frames": [],\
        "refId": "A"\
      \}\
    \}\
  \}\
\}}

**Comment by zspeaks** [comment]
Query Inspector when not using the variable

{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 \{\
  "request": \{\
    "url": "api/ds/query",\
    "method": "POST",\
    "data": \{\
      "queries": [\
        \{\
          "datasource": \{\
            "type": "grafana-iot-sitewise-datasource",\
            "uid": "URhhbtMSk"\
          \},\
          "refId": "A",\
          "maxPageAggregations": 1,\
          "queryType": "PropertyValue",\
          "assetIds": [\
            "ddc1eeee-9956-4eea-8dec-5594b0fbe861"\
          ],\
          "propertyId": "53df0857-d5a3-44f4-a946-bcbf0461a8a6",\
          "propertyAlias": "",\
          "region": "",\
          "datasourceId": 7,\
          "intervalMs": 500,\
          "maxDataPoints": 768\
        \}\
      ],\
      "range": \{\
        "from": "2023-10-09T19:03:33.658Z",\
        "to": "2023-10-09T19:08:33.658Z",\
        "raw": \{\
          "from": "now-5m",\
          "to": "now"\
        \}\
      \},\
      "from": "1696878213658",\
      "to": "1696878513658"\
    \},\
    "hideFromInspector": false\
  \},\
  "response": \{\
    "results": \{\
      "A": \{\
        "status": 200,\
        "frames": [\
          \{\
            "schema": \{\
              "name": "Demo Wind Farm Asset",\
              "refId": "A",\
              "fields": [\
                \{\
                  "name": "time",\
                  "type": "time",\
                  "typeInfo": \{\
                    "frame": "time.Time"\
                  \}\
                \},\
                \{\
                  "name": "Code",\
                  "type": "number",\
                  "typeInfo": \{\
                    "frame": "int64"\
                  \},\
                  "config": \{\}\
                \},\
                \{\
                  "name": "quality",\
                  "type": "string",\
                  "typeInfo": \{\
                    "frame": "string"\
                  \}\
                \}\
              ]\
            \},\
            "data": \{\
              "values": [\
                [\
                  1696603618000\
                ],\
                [\
                  300\
                ],\
                [\
                  "GOOD"\
                ]\
              ]\
            \}\
          \}\
        ],\
        "refId": "A"\
      \}\
    \}\
  \}\
\}}

**Comment by jrdeck** [comment]
Thanks @zspeaks - this issue is impacting one of our clients' factories at present. Appreciate your assistance with getting this resolved.
