### ISSUE TITLE
Error 500  run query on  SiteWise property value history for un-associated SiteWise data streams

### ISSUE THREAD

**Issue by janborch** [grafana/iot-sitewise-datasource#228]
**What happened**:

Query the SiteWise Datasource using Query Type: `Get Property Value History` 
specifying a `Property Alias` of an associated SiteWise data stream.

This type of query worked in past version of the plugin.

Query returns error status code 500

```
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "timeOrdering": "ASCENDING",
          "datasource": {
            "type": "grafana-iot-sitewise-datasource",
            "uid": "6ECVm78nz"
          },
          "refId": "A",
          "maxPageAggregations": 1,
          "queryType": "PropertyValueHistory",
          "propertyAlias": "/Rand/RAND089",
          "region": "",
          "propertyId": "",
          "assetIds": [],
          "datasourceId": 34,
          "intervalMs": 10000,
          "maxDataPoints": 1730
        }
      ],
      "range": {
        "from": "2023-10-10T07:04:26.903Z",
        "to": "2023-10-10T13:04:26.903Z",
        "raw": {
          "from": "now-6h",
          "to": "now"
        }
      },
      "from": "1696921466903",
      "to": "1696943066903"
    },
    "hideFromInspector": false
  },
  "response": {
    "message": "An error occurred within the plugin",
    "messageId": "plugin.downstreamError",
    "statusCode": 500,
    "traceID": ""
  }
}
```

**What you expected to happen**:

Query should return the timeseries data for this SiteWise datastream, below a sample query with an associated data stream.:

```
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "timeOrdering": "ASCENDING",
          "datasource": {
            "type": "grafana-iot-sitewise-datasource",
            "uid": "6ECVm78nz"
          },
          "refId": "A",
          "maxPageAggregations": 1,
          "queryType": "PropertyValueHistory",
          "propertyAlias": "/Rand/RAND004",
          "region": "",
          "propertyId": "",
          "assetIds": [],
          "datasourceId": 34,
          "intervalMs": 10000,
          "maxDataPoints": 1730
        }
      ],
      "range": {
        "from": "2023-10-10T07:03:42.217Z",
        "to": "2023-10-10T13:03:42.217Z",
        "raw": {
          "from": "now-6h",
          "to": "now"
        }
      },
      "from": "1696921422217",
      "to": "1696943022217"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "name": "H1 Rand02",
              "refId": "A",
              "meta": {
                "custom": {
                  "resolution": "RAW"
                }
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "rand02",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64"
                  },
                  "config": {}
                },
                {
                  "name": "quality",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1696938591738,
                  1696938596738,
                  1696938601735,
                  ...
```

**How to reproduce it (as minimally and precisely as possible)**:
Query a disassociated  data stream

**Anything else we need to know?**:

**Environment**:
- Grafana version: Amazon Manage Grafana  9.4
- Plugin version: 1.10.1 
- OS Grafana is installed on: NA
- User OS & Browser: NA
- Others:

**Comment by jhoulihan** [comment]
I encountered this issue too, using AWS Managed Grafana.  For an immediate workaround/fix, the datastreams can be associated with an asset in Sitewise and the data is able to be retrieved via AWS managed grafana.  
However, 
*********CAUTION***********,
Should you want to re-assign/remove the datastreams from an asset in Sitewise, for allocation later (eg to mitigate this work around for this bug) , Sitewise assigns a new UUID to the datastream (?????? really)  therefore you lose access to historical data a.k.a lost data, of that (previously) disassociated datastream in both Sitewise and AWS Managed Grafana! 

Expressing an opinion here... if I may use the analogy of a knife and fork representing datastream 1 and datastream 2.  If I place the knife and fork into a kitchen drawer (where the kitchen drawer represents a Sitewise asset).  I then take out of the kitchen drawer, **expecting** a knife and fork, but I get a spoon and a chopstick!!

**Comment by idastambuk** [comment]
Hi @janborch, thanks for submitting this. I managed to reproduce this with a disassociated asset. 

> This type of query worked in past version of the plugin.

Do you know which version of the plugin this worked in? I'm unable to find a version where it worked. 
Also, does this mean that the query for disassociated assets returned data, or just that it didn't return 500? 
Thanks!

**Comment by janborch** [comment]
It worked in plugin 1.5.1 , AMG 8.4

**Comment by idastambuk** [comment]
Hi @janborch I've managed to reproduce and we're working on a fix. You can follow updates in this ticket!

**Comment by fridgepoet** [comment]
Fixed by https://github.com/grafana/iot-sitewise-datasource/pull/231
