### ISSUE TITLE
Variable built from asset queries cannot be used within panel queries

### ISSUE THREAD

**Issue by alexhegg-aws** [grafana/iot-sitewise-datasource#232]
**What happened**: When a variable is defined within a dashboard built using the "List Assets" query type a drop-down selector is available to select a particular asset. This is useful for being able to quickly switch between multiple assets of the same type within a dashboard. In the latest versions of the plugin (tested on 1.10.1) trying to use this variable within a query for a panel results in the following error:
failed to fetch query data: InvalidParameter: 1 validation error(s) found. - minimum field size of 36, BatchGetAssetPropertyValueHistoryInput.Entries[0].AssetId.

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**: Using version 1.10.1 of the plugin, create a new dashboard variable using the "Asset List" query type. Create a new query in a panel using the "Get property value history" query type and select an Asset and Property. This query should succeed. Make sure the same asset as used in this query is selected in the variable drop-down

**Screenshots**
![grafana-error-1](https://github.com/grafana/iot-sitewise-datasource/assets/115964162/2bf51d77-23b5-4274-a9cb-e637cc7a51c4)
![grafana-error-2](https://github.com/grafana/iot-sitewise-datasource/assets/115964162/276a4b68-07c8-4ea2-a035-fcef3c979cc4)
![grafana-error-3](https://github.com/grafana/iot-sitewise-datasource/assets/115964162/bea41658-c3c9-441d-9d74-30d8e09a3b39)

**Anything else we need to know?**: This was observed under the latest IoT SiteWise plugin rollout for Amazon Managed Grafana. Using an asset variable was working under the previously deployed plugin version.

**Environment**:
- Grafana version: 8.4.7
- Plugin version: 1.10.1
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS + Chrome
- Others:

**Comment by idastambuk** [comment]
Hi @alexhegg-aws, I see the plugin version is listed as 1.10.0. We recently released 1.11.0 that fixed a bug with template variables - can you try upgrading the instance's version of the plugin to 1.11.0 and see if that solved it? Thanks!

**Comment by alexhegg-aws** [comment]
Hi @idastambuk I've tested under 1.11.0 and same issue is observed. Looks like this may be related to the issue you raised here https://github.com/grafana/iot-sitewise-datasource/issues/233 where the asset name (rather than the expected id) is used within the query.

**Comment by iwysiu** [comment]
Hi @alexhegg-aws ! I believe the issue's been fixed in OpenSearch plugin 1.11.1. I was able to reproduce this with OpenSearch 1.11.0 and Grafana 8.4.7, and it went away after I updated to the latest version. Sorry to ask you to update again, but can you try 1.11.1 and see if that fixes it?

**Comment by alexhegg-aws** [comment]
hi @iwysiu - I'd checked on SiteWise Plugin 1.11.1 earlier, and it appeared fixed then broke again. Think that was a side-effect of too many changes at once. Tested again now, and seems to be working. Will close this for now unless I can replicate an issue again.
