### ISSUE TITLE
Unable to access child assets when parent asset has multiple children through multiple hierarchies

### ISSUE THREAD

**Issue by farhan85** [grafana/iot-sitewise-datasource#264]
**What happened**: We have a customer that has set up their asset hierarchy where a parent asset has multiple child assets through multiple hierarchies, the dashboard is not retrieving the full list of all child assets.

**What you expected to happen**: When selecting a parent asset, all child assets of that parent asset is displayed in the drop-down selector

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**
Hierarchy of the customer's assets:
![01_asset_hierarchy](https://github.com/grafana/iot-sitewise-datasource/assets/4463436/358ed9b4-12f8-4248-83e0-7995472d04eb)

SiteWise console shows all child assets of the parent asset _3PH_Line_
![02_console_parent_asset](https://github.com/grafana/iot-sitewise-datasource/assets/4463436/37910684-ef6a-4401-b4bf-1ef5773007aa)

In the Grafana dashboard, variables are created to get the list of child assets

![03_grafana_variables_1](https://github.com/grafana/iot-sitewise-datasource/assets/4463436/a990bc22-ac2a-41a0-8ddd-c31a85d35396)

![03_grafana_variables_2](https://github.com/grafana/iot-sitewise-datasource/assets/4463436/02b1a643-900b-4272-ad91-d2c0bebb16ee)

However, when selecting the parent asset _3PH_Line_, only one child asset is displayed
![03_grafana_parent_asset](https://github.com/grafana/iot-sitewise-datasource/assets/4463436/a5797d30-21dc-4b60-a7d3-ac8e62ce7237)

**Anything else we need to know?**:

**Environment**: TBD
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by sarahzinger** [comment]
Hello, I believe some folks from AWS recently merged https://github.com/grafana/iot-sitewise-datasource/pull/261 which adds an "all" option to list all assets, is this the same issue?

I believe it was merged but not yet released, but is being tested.

**Comment by farhan85** [comment]
Yes that should address the same issue here. Thanks

**Comment by mitchlee-amzn** [comment]
Yes this has already been shipped, and will be in the next release.

**Comment by sarahzinger** [comment]
Just released this in https://github.com/grafana/iot-sitewise-datasource/releases/tag/v1.16.0
