### ISSUE TITLE
Query Editor: Clear Property field when the asset changes

### ISSUE THREAD

**Issue by idastambuk** [grafana/iot-sitewise-datasource#273]
**What happened**:

When we have property selected in the editor and we change the asset, property name becomes the ID instead of just being cleared. This means that if we submit this query, we will get "failed to fetch query data: ResourceNotFoundException: Property not found"

**What you expected to happen**:
Property Id should be cleared when asset ID is selected. 

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/grafana/iot-sitewise-datasource/assets/16140639/cf870238-b358-4276-8dfd-2950cc6ddc98

**Screenshots**

**Anything else we need to know?**:

We can select multiple assets, so the property shouldn't be cleared unless its asset is removed.

**Environment**:
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by tracy-french** [comment]
@idastambuk I'm from the AWS SiteWise team. I'll take this issue! Thank you! :)
