### ISSUE TITLE
Selected assets not visible on query 

### ISSUE THREAD

**Issue by chejimmy** [grafana/iot-sitewise-datasource#293]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4
- Plugin version: 
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by kevinwcyu** [comment]
Hi @chejimmy, can you add some details on what the issue is and how to reproduce it?

**Comment by kevinwcyu** [comment]
Hi @chejimmy, this looks like it may be a duplicate of https://github.com/grafana/iot-sitewise-datasource/issues/294 so I'm going to close this one off. If it's not, can you add some details on what the issue is and how to reproduce it?
