### ISSUE TITLE
Deprecate "ANY" data quality

### ISSUE THREAD

**Issue by hwandersman** [grafana/iot-sitewise-datasource#346]
**Is your feature request related to a problem? Please describe.**
I recently spent time debugging an issue where I set up a GetInterpolatedPropertyValues query and did not receive any data back when I should have. After a lot of digging I realized that I was using the "ANY" quality and the data I expected back was all "BAD". We [recently updated](https://github.com/grafana/iot-sitewise-datasource/pull/342) "ANY" to default to "GOOD" which should not be the assumption.

"ANY" is not a valid API prompt, so we should not support this in our datasource query.

**Describe the solution you'd like**
We should remove "ANY" as a quality option for all Get* APIs, and instead just have "GOOD"/"BAD"/"UNCERTAIN". We should default to "GOOD".

**Describe alternatives you've considered**
The only alternative is to actually implement "ANY" by querying the Get APIs with each possible quality and combining the values into a single response.

**Additional context**
None

**Comment by idastambuk** [comment]
@hwandersman In the description it says 

> "ANY" to default to "GOOD" which should not be the assumption.

But in the solution section it says

> We should default to "GOOD".

Can you clarify a bit better what you expect the end behavior to be? 

In the linked PR, we already removed the "ANY" dropdown option from the query editor and if there's no quality selected, it defaults to GOOD [here](https://github.com/grafana/iot-sitewise-datasource/blob/21bf1a5d812acf236d2e989a2f5cc00f6ebfa858/pkg/sitewise/api/property_interpolated.go#L40). This sounds to me like the solution proposed, lmk if I misunderstand!

**Comment by hwandersman** [comment]
Ah I see it was fully removed for the Interpolated query. We just need to do the same for the "Get property value aggregates" and "Get property value history" queries.
