### ISSUE TITLE
[HierarchyBrowser] implement 'trie view' for hierarchy

### ISSUE THREAD

**Issue by bymattoa** [grafana/iot-sitewise-datasource#47]
Tree should be collapsible with the first/root leaf being the selected asset:

example: https://codesandbox.io/s/yqw00p6vo1

- would be useful to have an info pop up modal to view the asset model details

**Comment by bymattoa** [comment]
We have a form drill down in pr #46 & #43 .

Working on adding collapsible hierarchies. TBD - how to implement the 'search' for child assets. The nice thing about the forms, is search is supported out of the box. The experience is not however, intuitive.

**Comment by ryantxu** [comment]
we have something reasonable, lets close this and open something more sepecific when requested
