### ISSUE TITLE
Grafana throws ExpiredTokenException after a certain period

### ISSUE THREAD

**Issue by sounavo** [grafana/iot-sitewise-datasource#52]
After setting up Sitewise plugin on Grafana it works for a while and then starts throwing "failed to fetch query data: ExpiredTokenException: status code: 403, request id: a9c25a27-c012-488d-a65a-18fc21a1939f" The error is gone after restarting the the ec2 running grafana. After a while the error comes back again.
![Screenshot 2020-11-16 at 19 13 07](https://user-images.githubusercontent.com/20790480/99291259-d1a16c80-283f-11eb-972a-25554e0915dd.png)
![Screenshot 2020-11-16 at 19 14 37](https://user-images.githubusercontent.com/20790480/99291361-fe558400-283f-11eb-81d4-757205310d14.png)

**Comment by bymattoa** [comment]
likely need a refresh hook in the credentials logic, to attempt to reload the file/re-request the assume role

**Comment by ryantxu** [comment]
Perhaps related to:
https://github.com/grafana/timestream-datasource/issues/11

And hopefully can be fixed with shared code.  Hopefully:
https://github.com/grafana/grafana-aws-sdk/tree/main/pkg/awsds

(This is copied from how core is doing cloudwatch)

**Comment by ryantxu** [comment]
@sounavo can you try again?  this is most likely fixed 

See the instructions on: https://github.com/grafana/iot-sitewise-datasource#aws-iot-sitewise-datasource-development-guide for how to get the latest dev build

**Comment by sounavo** [comment]
@ryantxu I still seem to be getting this issue after installing the new build. Happy to screenshare over slack if that helps
![image](https://user-images.githubusercontent.com/20790480/100086502-cd7fdb00-2e4d-11eb-93c7-ae30bda7f62f.png)
![image](https://user-images.githubusercontent.com/20790480/100086542-d96b9d00-2e4d-11eb-9380-ff11191394ff.png)

**Comment by bymattoa** [comment]
Hey @sounavo, I'm working to repro this in my own environment.

Quick question - can you confirm your auth type setup? Are you using the [ec2 instance role](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) to assume the `Assume Role ARN`? See below:

![Screen Shot 2020-11-24 at 12 47 16 PM](https://user-images.githubusercontent.com/19557121/100150162-163a9280-2e54-11eb-9380-d90efdb2af81.png)

If so, what is the maximum session duration for your ec2 and assume role arn roles?

![Screen Shot 2020-11-24 at 12 54 22 PM](https://user-images.githubusercontent.com/19557121/100150545-9fea6000-2e54-11eb-840d-2edb06062a1a.png)

**Comment by sounavo** [comment]
I am using ec2 instance role with max session 1 hour.
![image](https://user-images.githubusercontent.com/20790480/100154344-b5d44100-2ea5-11eb-9725-671b2cc9767d.png)
![image](https://user-images.githubusercontent.com/20790480/100154434-d8665a00-2ea5-11eb-9b77-30557845e098.png)

**Comment by bymattoa** [comment]
Hey @sounavo, just want to confirm - did you unzip the new build in the `/var/lib/grafana/plugins/` directory, and then restart the service?

![image](https://user-images.githubusercontent.com/19557121/100161372-29eef480-2e66-11eb-98e8-f9bf4ba6c8ae.png)

Hard to tell from the screenshot, but it looks like the plugin zip was downloaded with `wget`, but never extracted.

**Comment by sounavo** [comment]
Yes deleted the unzip line by mistake. But restoring it didn't fix the issue
![image](https://user-images.githubusercontent.com/20790480/100431831-ff38b200-3098-11eb-990b-c554a71e8fc5.png)

**Comment by bymattoa** [comment]
the unzip path there is for darwin. Are you running the grafana server on an OSX machine? or ec2 instance?

**Comment by ryantxu** [comment]
@sounavo can you add more details if you are still having errors.  I assume this is fixed now with recent releases

**Comment by sounavo** [comment]
I can confirm that this issue is now fixed on the main branch.
