### ISSUE TITLE
Allow user to provide custom certificate when use plugin

### ISSUE THREAD

**Issue by macrovve** [grafana/iot-sitewise-datasource#74]
The current release [SiteWise Edge](https://aws.amazon.com/blogs/iot/introducing-aws-iot-sitewise-edge/) bring SiteWise ability to the edge. SiteWise Edge has almost same APIs as the SiteWise except It introduces new region call `Edge` and use localhost signed certificate. 

In order to support SiteWise Edge, we could disable ssl verify when the region is `Edge`, or we find a way to pass certificate to the plugin. The latter one is better in my opinion.

**Comment by bymattoa** [comment]
@ryantxu: I'm thinking we could store the cert as secure json data.

@macrovve:  how many other edge products are there that could have overlap with grafana?

**Comment by macrovve** [comment]
DynamoDB Local could be one, but I didn't see there is a  plugin for DynamoDB.

**Comment by ryantxu** [comment]
Is it a custom certificate to the aws client?  Is this a standard field?  (Check the config options on prometheus/influx) or a different kind of certificate?

**Comment by ryantxu** [comment]
Is this common in other aws services?  Or only iot-sitewise?

**Comment by macrovve** [comment]
For now, it’s only iot sitewise edge.

**Comment by ryantxu** [comment]
My real question is if this should be added to this repo, or the grafana-aws-sdk library (where it can be shared with other aws services)

**Comment by macrovve** [comment]
> Is it a custom certificate to the aws client? Is this a standard field? (Check the config options on prometheus/influx) or a different kind of certificate?

It is a standard TLS certificate, we use this certificate for establishing the TLS connection and uses access key and secret key for authentication

**Comment by macrovve** [comment]
> My real question is if this should be added to this repo, or the grafana-aws-sdk library (where it can be shared with other aws services)

After talked with more people, there is not much edge service right now, needless to say that service need custom certificate, so I think keeping it to this repo for now would be better.

**Comment by macrovve** [comment]
One way to do this is we are going to pass certificate to the plugin via browser. But if Grafana is running via docker container,  the customer have to mount their certificate client when they start the container. Will this be a good approach? @ryantxu
