### ISSUE TITLE
IoT SiteWise Grafana Plugin Giving "Metric request error"

### ISSUE THREAD

**Issue by emrahacikalin** [grafana/iot-sitewise-datasource#97]
Metric request error still exists (https://github.com/grafana/iot-sitewise-datasource/issues/81)

**Comment by emrahacikalin** [comment]
Upgraded Grafana version to v8.0.0 (41f0542c1e). However, The problem still exists.

**Comment by ryantxu** [comment]
From the datasource page, are you able to click "Save and test"?

![image](https://user-images.githubusercontent.com/705951/121601100-53cec980-c9fa-11eb-9c04-343ea3b4b639.png)

**Comment by emrahacikalin** [comment]
Yes. Here is the result 

![image](https://user-images.githubusercontent.com/52149102/121606319-97572100-ca56-11eb-99b6-60fc7d39dcf4.png)

**Comment by ryantxu** [comment]
do any queries work?  and you get this sometimes, or is this for all queries?

**Comment by emrahacikalin** [comment]
The queries that were defined before the problem occurred are working properly.

![image](https://user-images.githubusercontent.com/52149102/121640278-64cd1880-ca96-11eb-8968-95c0af348d5e.png)

This case constantly occurs after the problem showed up. We can't add a new query by using Asset Browser by Model.

**Comment by emrahacikalin** [comment]
@ryantxu do you have any comment on this?
